<a href="https://colab.research.google.com/github/ItokianaMahenintsoa/python-data-analysis/blob/main/Python_Data_Analysis_Started_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7 -5, 3])
obj

,0
0,4
1,2
2,3


In [4]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(2), np.int64(3)]
Length: 3, dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

,0
d,4
b,7
a,-5
c,3


In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2["a"]

np.int64(-5)

In [9]:
obj2["d"] = 6
obj2[["c", "a", "d"]]

,0
c,3
a,-5
d,6


In [10]:
obj2[obj2 > 0]

,0
d,6
b,7
c,3


In [11]:
obj2 * 2

,0
d,12
b,14
a,-10
c,6


In [12]:
import numpy as np

In [13]:
np.exp(obj2)

,0
d,403.428793
b,1096.633158
a,0.006738
c,20.085537


In [14]:
"b" in obj2

True

In [15]:
"e" in obj2

False

In [16]:
sdata = {"Ohio": 35000, "Texas":71000, "Oregan":1600, "Utah":5000}

In [17]:
obj3 = pd.Series(sdata)

In [18]:
obj3

,0
Ohio,35000
Texas,71000
Oregan,1600
Utah,5000


In [19]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregan': 1600, 'Utah': 5000}

In [20]:
states = ["California", "Ohio", "Oregan", "Texas"]

In [21]:
obj4 = pd.Series(sdata, index=states)
obj4

,0
California,NaN
Ohio,35000.0
Oregan,1600.0
Texas,71000.0


In [22]:
pd.isna(obj4)

,0
California,True
Ohio,False
Oregan,False
Texas,False


In [23]:
pd.notna(obj4)

,0
California,False
Ohio,True
Oregan,True
Texas,True


In [24]:
obj4.isna()

,0
California,True
Ohio,False
Oregan,False
Texas,False


In [25]:
obj3

,0
Ohio,35000
Texas,71000
Oregan,1600
Utah,5000


In [26]:
obj4

,0
California,NaN
Ohio,35000.0
Oregan,1600.0
Texas,71000.0


In [27]:
obj3 + obj4

,0
California,NaN
Ohio,70000.0
Oregan,3200.0
Texas,142000.0
Utah,NaN


In [28]:
obj4.name = "population"

In [29]:
obj4.index.name = "state"
obj4

,population
state,
California,NaN
Ohio,35000.0
Oregan,1600.0
Texas,71000.0


In [30]:
obj = pd.Series([4, 7, -5, 3])
obj

,0
0,4
1,7
2,-5
3,3


In [31]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

,0
Bob,4
Steve,7
Jeff,-5
Ryan,3


In [32]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada","Nevada", "Nevada"], "year": [2000, 2001, 2002, 2001, 2002, 2003], "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [33]:
frame = pd.DataFrame(data)
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [34]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [35]:
frame.tail()

,state,year,pop
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [36]:
pd.DataFrame(data, columns=["year", "state", "pop"])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [37]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
frame2["state"]

,state
0,Ohio
1,Ohio
2,Ohio
3,Nevada
4,Nevada
5,Nevada


In [40]:
frame2.year

,year
0,2000
1,2001
2,2002
3,2001
4,2002
5,2003


In [41]:
frame2.loc[1]

,1
year,2001
state,Ohio
pop,1.7
debt,NaN


In [42]:
frame2.iloc[2]

,2
year,2002
state,Ohio
pop,3.6
debt,NaN


In [43]:
frame2["debt"] = 16.5
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,16.5
1,2001,Ohio,1.7,16.5
2,2002,Ohio,3.6,16.5
3,2001,Nevada,2.4,16.5
4,2002,Nevada,2.9,16.5
5,2003,Nevada,3.2,16.5


In [44]:
frame2["debt"] = np.arange(6.)
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,0.0
1,2001,Ohio,1.7,1.0
2,2002,Ohio,3.6,2.0
3,2001,Nevada,2.4,3.0
4,2002,Nevada,2.9,4.0
5,2003,Nevada,3.2,5.0


In [45]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
frame2["debt"] = val
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [46]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

,year,state,pop,debt,eastern
0,2000,Ohio,1.5,NaN,True
1,2001,Ohio,1.7,NaN,True
2,2002,Ohio,3.6,NaN,True
3,2001,Nevada,2.4,NaN,False
4,2002,Nevada,2.9,NaN,False
5,2003,Nevada,3.2,NaN,False


In [47]:
del frame2["eastern"]

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002:2.9}}
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [50]:
frame3 = pd.DataFrame(populations)
frame3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [51]:
frame3.T

,2000,2001,2002
Ohio,1.5,1.7,3.6
Nevada,NaN,2.4,2.9


In [52]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9
2003,NaN,NaN


In [53]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4


In [54]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [55]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [56]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [57]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [58]:
index[1:]

Index(['b', 'c'], dtype='object')

In [60]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [61]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [62]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

,0
0,1.5
1,-2.5
2,0.0


In [63]:
obj2.index is labels

True

In [64]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [65]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [66]:
"Ohio" in frame3.columns

True

In [67]:
2003 in frame3.index

False

In [68]:
pd.Index(["foo", "foo", "bar", "bar"])


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Reindexing

In [69]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

,0
d,4.5
b,7.2
a,-5.3
c,3.6


In [70]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

,0
a,-5.3
b,7.2
c,3.6
d,4.5
e,NaN


In [71]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

,0
0,blue
2,purple
4,yellow


In [72]:
obj3.reindex(np.arange(6), method="ffill")

,0
0,blue
1,blue
2,purple
3,purple
4,yellow
5,yellow


In [73]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas","California"])
frame

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [74]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

,Ohio,Texas,California
a,0.0,1.0,2.0
b,NaN,NaN,NaN
c,3.0,4.0,5.0
d,6.0,7.0,8.0


In [75]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [76]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0
e,4.0


In [77]:
new_obj = obj.drop("c")
new_obj

,0
a,0.0
b,1.0
d,3.0
e,4.0


In [78]:
obj.drop(["d", "c"])

,0
a,0.0
b,1.0
e,4.0


In [79]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [80]:
data.drop(index=["Colorado", "Ohio"])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [81]:
data.drop(columns=["two"])

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [82]:
data.drop("two", axis=1)

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [83]:
data.drop(["two", "four"], axis="columns")

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [84]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0


In [85]:
obj["b"]

np.float64(1.0)

In [86]:
obj[1]

/tmp/ipykernel_174/2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [87]:
obj[2:4]

,0
c,2.0
d,3.0


In [88]:
obj[["b", "a", "d"]]

,0
b,1.0
a,0.0
d,3.0


In [89]:
obj[[1, 3]]

/tmp/ipykernel_174/2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]


,0
b,1.0
d,3.0


In [90]:
obj[[1,3]]

/tmp/ipykernel_174/1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


,0
b,1.0
d,3.0


In [91]:
obj[obj < 2]

,0
a,0.0
b,1.0


In [92]:
obj.loc[["b", "a", "d"]]

,0
b,1.0
a,0.0
d,3.0


In [93]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj1



,0
2,1
0,2
1,3


In [94]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

,0
a,1
b,2
c,3


In [95]:
obj1[[0, 1, 2]]

,0
0,2
1,3
2,1


In [96]:
obj2[[0, 1, 2]]

/tmp/ipykernel_174/2599987575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]


,0
a,1
b,2
c,3


In [97]:
obj2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [98]:
obj1.iloc[[0, 1, 2]]


,0
2,1
0,2
1,3


In [99]:
obj2.iloc[[0, 1, 2]]

,0
a,1
b,2
c,3


In [100]:
obj2.loc["b": "c"] = 5
obj2

,0
a,1
b,5
c,5


In [101]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [102]:
data["two"]

,two
Ohio,1
Colorado,5
Utah,9
New York,13


In [103]:
data[["three", "one"]]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [104]:
data[:2]

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7


In [105]:
data[data["three"] > 5 ]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [106]:
data < 5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [107]:
data[data < 5] = 0
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [108]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [109]:
data.loc["Colorado"]

,Colorado
one,0
two,5
three,6
four,7


In [110]:
data.loc[["Colorado", "New York"]]

,one,two,three,four
Colorado,0,5,6,7
New York,12,13,14,15


In [111]:
data.loc["Colorado", ["two", "three"]]

,Colorado
two,5
three,6


In [112]:
data.iloc[2]

,Utah
one,8
two,9
three,10
four,11


In [113]:
data.iloc[[2, 1]]

,one,two,three,four
Utah,8,9,10,11
Colorado,0,5,6,7


In [114]:
data.iloc[2, [3, 0, 1]]

,Utah
four,11
one,8
two,9


In [115]:
data.iloc[[1, 2], [3, 0, 1]]

,four,one,two
Colorado,7,0,5
Utah,11,8,9


In [116]:
data.loc[:"Utah", "two"]

,two
Ohio,0
Colorado,5
Utah,9


In [117]:
data.iloc[:, :3][data.three > 5]

,one,two,three
Colorado,0,5,6
Utah,8,9,10
New York,12,13,14


In [118]:
data.loc[data.three >= 2]

,one,two,three,four
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [119]:
ser = pd.Series(np.arange(3.))
ser

,0
0,0.0
1,1.0
2,2.0


In [120]:
ser[-1]

KeyError: -1

In [121]:
ser

,0
0,0.0
1,1.0
2,2.0


In [122]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

/tmp/ipykernel_174/821879068.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [123]:
ser.iloc[-1]

np.float64(2.0)

In [124]:
ser[:2]

,0
0,0.0
1,1.0


In [125]:
data.loc[:, "one"] = 1
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,1,9,10,11
New York,1,13,14,15


In [126]:
data.iloc[2] = 5
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,5,5,5,5
New York,1,13,14,15


In [127]:
data.loc[data["four"] > 5] = 3
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [128]:
data.loc[data["four"] > 5 ] = 3
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [129]:
data.loc[data.three == 5, "three"] = 6
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,6,5
New York,3,3,3,3


In [130]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [131]:
s1

,0
a,7.3
c,-2.5
d,3.4
e,1.5


In [132]:
s2

,0
a,-2.1
c,3.6
e,-1.5
f,4.0
g,3.1


In [133]:
s1 + s2

,0
a,5.2
c,1.1
d,NaN
e,0.0
f,NaN
g,NaN


In [134]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [135]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list("bde"), index=["Utah", "Ohio","Texas", "Oregon"])
df2

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [136]:
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


In [137]:
df1 = pd.DataFrame({"A": [1, 2]})

In [138]:
df2 = pd.DataFrame({"B": [3, 4]})

In [139]:
df1

,A
0,1
1,2


In [140]:
df2

,B
0,3
1,4


In [141]:
df1 + df2

,A,B
0,NaN,NaN
1,NaN,NaN


In [142]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list("abcd"))

In [143]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list("abcde"))

In [144]:
df2.loc[1, "b"] = np.nan

In [145]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [146]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [147]:
df1 + df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [148]:
df1.add(df2, fill_value = 0 )

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [149]:
1/df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [150]:
df1.rdiv(1)

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [151]:
df1.reindex(columns=df2.columns, fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [152]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [153]:
arr[0]

array([0., 1., 2., 3.])

In [154]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [155]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [156]:
series = frame.iloc[0]


In [157]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [158]:
series

,Utah
b,0.0
d,1.0
e,2.0


In [159]:
frame - series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


In [160]:
series2 = pd.Series(np.arange(3), index=["b","e", "f"])
series2

,0
b,0
e,1
f,2


In [161]:
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [162]:
series3 = frame["d"]

In [163]:
series3

,d
Utah,1.0
Ohio,4.0
Texas,7.0
Oregon,10.0


In [164]:
frame.sub(series3, axis="index")

,b,d,e
Utah,-1.0,0.0,1.0
Ohio,-1.0,0.0,1.0
Texas,-1.0,0.0,1.0
Oregon,-1.0,0.0,1.0


In [165]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

,b,d,e
Utah,-0.190953,0.230963,0.699422
Ohio,-0.733684,2.696296,-2.994311
Texas,-0.284949,-1.094907,0.770789
Oregon,0.000565,0.064619,-2.543760


In [166]:
np.abs(frame)

,b,d,e
Utah,0.190953,0.230963,0.699422
Ohio,0.733684,2.696296,2.994311
Texas,0.284949,1.094907,0.770789
Oregon,0.000565,0.064619,2.543760


In [167]:
def f1(x):
  return x.max() - x.min()

In [168]:
frame.apply(f1)

,0
b,0.734249
d,3.791203
e,3.765100


In [169]:
frame.apply(f1, axis="columns")

,0
Utah,0.890375
Ohio,5.690607
Texas,1.865696
Oregon,2.608379


In [170]:
def f2(x):
  return pd.Series([x.min(), x.max()], index=["min", "max"])

In [171]:
frame.apply(f2)

,b,d,e
min,-0.733684,-1.094907,-2.994311
max,0.000565,2.696296,0.770789


In [172]:
def my_format(x):
  return f"{x:.2f}"

In [174]:
frame.map(my_format)

,b,d,e
Utah,-0.19,0.23,0.70
Ohio,-0.73,2.70,-2.99
Texas,-0.28,-1.09,0.77
Oregon,0.00,0.06,-2.54


In [175]:
frame["e"].map(my_format)

,e
Utah,0.70
Ohio,-2.99
Texas,0.77
Oregon,-2.54


In [176]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

,0
d,0
a,1
b,2
c,3


In [177]:
obj.sort_index()

,0
a,1
b,2
c,3
d,0


In [178]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b","c"])
frame

,d,a,b,c
three,0,1,2,3
one,4,5,6,7


In [179]:
frame.sort_index()


,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [180]:
frame.sort_index(axis="columns")

,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [181]:
frame.sort_index(axis="columns",ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [182]:
obj = pd.Series([4, 7, -3, 2])

In [183]:
obj.sort_values()

,0
2,-3
3,2
0,4
1,7


In [185]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

,0
0,4.0
1,NaN
2,7.0
3,NaN
4,-3.0
5,2.0


In [186]:
obj.sort_values()

,0
4,-3.0
5,2.0
0,4.0
2,7.0
1,NaN
3,NaN


In [189]:
obj.sort_values(na_position="first")

,0
1,NaN
3,NaN
4,-3.0
5,2.0
0,4.0
2,7.0


In [191]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a":[0, 1, 0, 1]})
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [192]:
frame.sort_values("b")

,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [193]:
frame.sort_values(["a", "b"])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [194]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

,0
0,6.5
1,1.0
2,6.5
3,4.5
4,3.0
5,2.0
6,4.5


In [195]:
obj.rank(method="first")

,0
0,6.0
1,1.0
2,7.0
3,4.0
4,3.0
5,2.0
6,5.0


In [196]:
obj.rank(ascending=False)

,0
0,1.5
1,7.0
2,1.5
3,3.5
4,5.0
5,6.0
6,3.5


In [197]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],  "c": [-2, 5, 8, -2.5]})
frame

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [199]:
frame.rank(axis="columns")

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [201]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

,0
a,0
a,1
b,2
b,3
c,4


In [202]:
obj.index.is_unique

False

In [203]:
obj["a"]

,0
a,0
a,1


In [204]:
obj["c"]

np.int64(4)

In [205]:
df = pd.DataFrame(np.random.standard_normal((5, 3)), index=["a", "a", "b", "b","c"])
df

,0,1,2
a,1.345948,-1.559141,0.337160
a,-1.155027,1.170667,-0.456653
b,0.508549,-0.365019,-0.277522
b,1.212370,2.100110,-0.698300
c,0.742163,0.143531,0.174249


In [206]:
df.loc["b"]

,0,1,2
b,0.508549,-0.365019,-0.277522
b,1.212370,2.100110,-0.698300


In [208]:
df.loc["c"]

,c
0,0.742163
1,0.143531
2,0.174249


In [209]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75,-1.3]], index=["a", "b", "c", "d"], columns=["one", "two"])
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [210]:
df.sum()

,0
one,9.25
two,-5.80


In [211]:
df.sum(axis="columns")

,0
a,1.40
b,2.60
c,0.00
d,-0.55


In [212]:
df.sum(axis="index", skipna=False)

,0
one,NaN
two,NaN


In [214]:
df.mean(axis="columns")

,0
a,1.400
b,1.300
c,NaN
d,-0.275


In [215]:
df.idxmax()

,0
one,b
two,d


In [216]:
df.cumsum()

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [217]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [218]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

,0
count,16
unique,3
top,a
freq,8


In [219]:
price = pd.read_pickle("sample_data/yahoo_price.pkl")

In [220]:
volume = pd.read_pickle("sample_data/yahoo_volume.pkl")

In [222]:
returns = price.pct_change()
returns.tail()

,AAPL,GOOG,IBM,MSFT
Date,,,,
2016-10-17,-0.000680,0.001837,0.002072,-0.003483
2016-10-18,-0.000681,0.019616,-0.026168,0.007690
2016-10-19,-0.002979,0.007846,0.003583,-0.002255
2016-10-20,-0.000512,-0.005652,0.001719,-0.004867
2016-10-21,-0.003930,0.003011,-0.012474,0.042096


In [223]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.49976361144151144)

In [224]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [225]:
returns.corr()

,AAPL,GOOG,IBM,MSFT
AAPL,1.000000,0.407919,0.386817,0.389695
GOOG,0.407919,1.000000,0.405099,0.465919
IBM,0.386817,0.405099,1.000000,0.499764
MSFT,0.389695,0.465919,0.499764,1.000000


In [226]:
returns.cov()

,AAPL,GOOG,IBM,MSFT
AAPL,0.000277,0.000107,0.000078,0.000095
GOOG,0.000107,0.000251,0.000078,0.000108
IBM,0.000078,0.000078,0.000146,0.000089
MSFT,0.000095,0.000108,0.000089,0.000215


In [228]:
returns.corrwith(returns["IBM"])

,0
AAPL,0.386817
GOOG,0.405099
IBM,1.000000
MSFT,0.499764


In [229]:
returns.corrwith(volume)

,0
AAPL,-0.075565
GOOG,-0.007067
IBM,-0.204849
MSFT,-0.092950


In [230]:
obj = pd.Series(["c", "a", "d", "a", "a", "b","b", "c", "c"])

In [232]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [233]:
obj.value_counts()

,count
c,3
a,3
b,2
d,1


In [236]:
pd.value_counts(obj.to_numpy(), sort=False)

/tmp/ipykernel_174/164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)


,count
c,3
a,3
d,1
b,2


In [237]:
obj

,0
0,c
1,a
2,d
3,a
4,a
5,b
6,b
7,c
8,c


In [238]:
mask = obj.isin(["b", "c"])
mask

,0
0,True
1,False
2,False
3,False
4,False
5,True
6,True
7,True
8,True


In [239]:
obj[mask]

,0
0,c
5,b
6,b
7,c
8,c


In [240]:
to_match = pd.Series(["c", "a", "b", "b", "c","a"])

In [241]:
unique_vals = pd.Series(["c", "b", "a"])

In [242]:
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [243]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4], "Qu2": [2, 3, 1, 2, 3], "Qu3": [1, 5, 2, 4, 4]})
data

,Qu1,Qu2,Qu3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [244]:
data["Qu1"].value_counts().sort_index()

,count
Qu1,
1,1
3,2
4,2


In [245]:
result = data.apply(pd.value_counts).fillna(0)
result

/tmp/ipykernel_174/1382616601.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


,Qu1,Qu2,Qu3
1,1.0,1.0,1.0
2,0.0,2.0,1.0
3,2.0,2.0,0.0
4,2.0,0.0,2.0
5,0.0,0.0,1.0


In [246]:
 data = pd.DataFrame({"a": [1, 1, 1, 2, 2],"b": [0, 0, 1, 0, 0]})
 data

,a,b
0,1,0
1,1,0
2,1,1
3,2,0
4,2,0


In [247]:
data.value_counts()

,,count
a,b,
1,0,2
2,0,2
1,1,1
